# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Taekyung Park
description:      Hello!
url:              https://kibi0620.github.io
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           Taekyung Park
  url:            https://kibi0620.github.io
  email:          kibi0620@gmail.com, ptk620@gmail.com
  github:         kibi0620.github.io
  linkedin:       https://www.linkedin.com/in/tae-kyung-park/

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

repo:             https://github.com/kibi0620/kibi0620.github.io
google_analytics: UA-160028891-1
# Sidebar link settings
# sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
